### ISSUE TITLE
Não tem README descrevendo o que este repositório contém

### ISSUE THREAD

**Issue by decko** [culturagovbr/sistema-nacional-cultura#1]

**Comment by avaloni** [comment]
Faltou o commit, agora tem uma bem básica, qualquer sugestão de melhoria é bem-vinda.

**Comment by diegoaguilera** [comment]
Fiz uma melhoria, mas acho que vale a pena descrever a arquitetura tecnologica Aval

**Comment by diegoaguilera** [comment]
Fox e Christian fizeram um readme, com tutorial de instalação do repo.
