### ISSUE TITLE
Informações "estranhas" na tela inicial

### ISSUE THREAD

**Issue by Matheusss03** [culturagovbr/sistema-nacional-cultura#100]
Frases sem sentido presentes na tela inicial do sistema

<img src="https://raw.githubusercontent.com/wiki/culturagovbr/sistema-nacional-cultura/images/errorr.png">

**Comment by izacristina** [comment]
@AnaOlivei Manda o texto que é pra colocar, por favor

**Comment by izacristina** [comment]
@AnaOlivei Relembrando vcs de mandarem o texto pra colocar

**Comment by AnaOlivei** [comment]
@izacristina eu mandei para o seu e-mail no mesmo dia que fizemos a reunião, mas mando de novo sem problemas. Até abri uma issue onde mostrei o texto.

**Comment by izacristina** [comment]
@AnaOlivei é esse aqui? https://github.com/culturagovbr/sistema-nacional-cultura/issues/164

**Comment by AnaOlivei** [comment]
@izacristina exatamente.

**Comment by izacristina** [comment]
@AnaOlivei a que você mandou, da issue #164 é a tela que aparece depois que o usuário cadastra o ente federado, interlocutor e etc, já essa aqui aparece assim que ele entra depois de confirmar seu e-mail, quando ainda não cadastrou o ente federado, deu pra entender?

**Comment by AnaOlivei** [comment]
@izacristina O título deve ser: Bem-Vindo ao Sistema Nacional de Cultura e o texto conforme a imagem:
![image](https://user-images.githubusercontent.com/32340472/42241058-aad3db76-7edf-11e8-818d-e92b3188c4a7.png)
