### ISSUE TITLE
Template para a tela de recuperar a senha não usa estilo do SNC

### ISSUE THREAD

**Issue by decko** [culturagovbr/sistema-nacional-cultura#104]
A tela de recuperar a senha está utilizando o template padrão do Django, quando deveria utilizar o template próprio do SNC.

**Comment by matheusbsilva** [comment]
O caminho para os templates estava errado, e então o sistema não conseguiu encontrar nenhum template para sobrescrever os templates padrões do Django.

**Comment by decko** [comment]
Os testes para a funcionalidade foram criados e estão passando. As configurações nos servidores de produção e homologação foram alteradas para apontar para os caminhos corretos.
