### ISSUE TITLE
Reimportação dos dados da data de publicação do acordo

### ISSUE THREAD

**Issue by AnaOlivei** [culturagovbr/sistema-nacional-cultura#111]
Atualizar os dados da plataforma à partir da planilha da ROSE, que está mais correta.

Especificamente a data de publicação está em desacordo, a da planilha é a mais correta.

**Comment by AnaOlivei** [comment]
Isso não é super urgente pois conseguimos resolver pontualmente na hora.

**Comment by matheusbsilva** [comment]
@AnaOlivei Poderia enviar a planilha via email? izabela.cardoso@lablivre.wiki.br

**Comment by AnaOlivei** [comment]
@matheusbsilva enviei a planilha com as datas de publicações e os hiperlinks para o e-mail informado.
