### ISSUE TITLE
Diligência de arquivos recebidos

### ISSUE THREAD

**Issue by matheusbsilva** [culturagovbr/sistema-nacional-cultura#114]
Eu, como gestor do ministério, gostaria de poder emitir uma diligência para cada arquivo recebido, de cada componente.

**Critérios de aceitação:**
- [ ] Testes para cada camada envolvida
- [ ] Interface para enviar a diligência
- [ ] Informações sobre a diligência:
  - [ ] Data de envio do arquivo
  - [ ] Nome original do arquivo
  - [ ] Usuário cadastrador
  - [ ] Data da diligência
  - [ ] Texto da diligência  
  - [ ] Usuário que enviou a diligência
  - [ ] Situação do arquivo enviado

**Comment by matheusbsilva** [comment]
Por mais que exista mais de um arquivo por componente na model do Plano de Trabalho, somente um deles é avaliado no processo de adesão, logo criar uma funcionalidade para avaliar cada arquivo de um componente teria o mesmo objetivo que avaliar o componente em si, então essa funcionalidade não faz sentido.

**Comment by decko** [comment]
Isso foi validado com a área de negócio?

**Comment by decko** [comment]
Confirmei pela manhã do dia 02/02, com Teresa, sobre a necessidade desta história. Confirmando então a hipótese da equipe de que a Diligencia deve existir para cada componente apenas, e não para cada arquivo enviado.
