### ISSUE TITLE
Diligência de componente

### ISSUE THREAD

**Issue by matheusbsilva** [culturagovbr/sistema-nacional-cultura#115]
Eu, como gestor do ministério, gostaria de poder emitir uma diligência para cada componente do plano de trabalho.

**Critérios de Aceitação**
 - [x] Testes para cada camada envolvida 
 - [x] Interface para enviar a diligência
    - [x] Organizar elementos na tela #123 
 - [x] Interface de consulta de histórico:
    - [x] Colocar histórico de diligências em um card #122
 - [x] Informações sobre a diligência: 
   - [x] Data da diligência
   - [x] Texto da diligência
   - [x] Usuário que enviou a diligência
   - [x] Situação da diligência

**Comment by decko** [comment]
# Especificação
Cada componente do plano de trabalho do SNC deve permitir o envio de uma redação de diligencia na qual o servidor responsável possa registrar sua analise dos elementos fundantes do componente em questão. 

## Interface
A interface deve focar em cinco informações:
- Texto de Diligência
- Classificação (Motivo)
- Histórico de Diligências do Componente para o mesmo ente federado.
- Informações sobre o Arquivo enviado
- Botões de ação

### Interface do Histórico
O componente deve conter o nome do usuário, o motivo da diligencia, data e resumo em 150 primeiros caracteres do texto da diligencia, ordenados pelos últimos três registros. O componente deve possibilitar o reuso em outros locais do sistema.

### Texto da Diligencia
Atualmente ja existe um componente de formatação de texto para enviar a diligência, deve-se utilizá-lo. Trata-se de um compontente TextField, sem limites de caracteres.

### Botoes de ação
Deve conter um botão para enviar a diligencia e outro para cancelar o envio da diligencia.

### Classificação (motivo)
Quando o arquivo for aprovado, as opções de classificar a situação do arquivo (na interface de Diligência) devem ser desabilitadas.
Quando o arquivo for reprovado, as opções de classificar a situação do arquivo devem aparecer, obedecendo a seguinte lista: 
    - Arquivo danificado
    - Arquivo incompleto
    - Arquivo incorreto

### Informações  sobre o Arquivo enviado
Deve ser mostrado o nome do arquivo, a data de envio e nome do ente federado.

**Comment by matheusbsilva** [comment]
# Situação da Issue:

## O que foi feito:
* Implementado a lógica para criar as diligências referentes aos componentes do Plano de Trabalho;
* Criado uma tela _(template)_ para a criação da diligência;
* Generalizada a relação entre componente e seu respectivo arquivo e situação;
* Implementado a opção de escolher uma situação do arquivo ao criar uma diligência;
* Configurado novo caminho para o armazenamento dos arquivos dos componentes, seguindo o padrão: ```{id_entefederado}/docs/{componente}/{nome_arquivo}``` .

### Dificuldades Enfrentadas:
* Cada componente tinha um nome diferente para o _field_ do arquivo e da situação.

## O que falta fazer:
 ### Interface para enviar a diligência, Interface de consulta de histórico
- Para completar o template referente a diligência falta aplicar o estilo de cards para as informações do histórico da diligência. (#122) 
- Organizar a posição dos elementos na tela. (#123)

### Refatoração
- Associar os botões de avaliação (positivo/negativo) para a tela de criação da diligência do componente respectivo.
- Alterar referências aos arquivos dos componentes, visto que o campo padrão foi modificado em todos os componentes.

### Testes para cada camada envolvida  
- Como o desenvolvimento da funcionalidade ainda está em progresso, os testes continuam sendo implementados e refatorados.

**Comment by decko** [comment]
A funcionalidade está em testes com a área de negócios desde 27/03. Preparar para enviar à Produçao até 06/04.
