### ISSUE TITLE
Associar os botões de avaliação (positivo/negativo) para a tela de criação da diligência do componente respectivo.

### ISSUE THREAD

**Issue by decko** [culturagovbr/sistema-nacional-cultura#124]

**Comment by luizfpinheiro** [comment]
### Sobre a avaliação dos documentos enviados, em cada um dos componentes:
O usuário deve fazer a diligência em ambos os casos de avaliação (aprovado/não aprovado). 
- Quando aprovado, a tela de criação de diligência é aberta com a opção para classificar a situação do arquivo como "Concluída".
- Quando reprovado, a tela de criação de diligência é aberta com as opções para classificar a situação do arquivo como "Arquivo danificado", "Arquivo incorreto" ou "Arquivo incompleto".
