### ISSUE TITLE
Criar o cadastro de Conselheiros do Municipio

### ISSUE THREAD

**Issue by diegodorgam** [culturagovbr/sistema-nacional-cultura#13]
Permitir o cadastramento dos conselheiros do município, com os dados disponíveis na consulta aberta.

**Comment by avaloni** [comment]
Falta só disponibilizar esses dados na consulta aberta

**Comment by uira** [comment]
Então, precisamos integrar esses dados, dar ID da Cultura para esses conselheiros, para utilizarem os sistemas de participação do MinC

**Comment by chris-redfield** [comment]
já implementado <3
