### ISSUE TITLE
Permitir que seja feita a Diligência Geral mesmo que não haja arquivos

### ISSUE THREAD

**Issue by Matheusss03** [culturagovbr/sistema-nacional-cultura#132]
Atualmente o sistema não consegue carregar a página de Diligência Geral caso um dos arquivos dos componentes não tenha sido enviado.

**Comment by matheusbsilva** [comment]
Resolvido em https://github.com/culturagovbr/sistema-nacional-cultura/commit/d8dd6e5e1faecf7757971e298552e61aeb88307a
