### ISSUE TITLE
Erro ao alterar situação do ente federado para Publicado no DOU

### ISSUE THREAD

**Issue by matheusbsilva** [culturagovbr/sistema-nacional-cultura#135]
Ao alterar o estado do processo do ente federado para publicado no DOU através da tela de gestão ocorrer um erro com o field ```data_envio``` pois ele não está sendo carregado com nenhum valor.

**Comment by matheusbsilva** [comment]
O problema se encontra na obrigatoriedade do campo na classe da model ArquivoComponente, deveria receber o parâmetro blank=True, segundo essa [referência](https://stackoverflow.com/questions/2771676/django-datetime-issues-default-datetime-now)

**Comment by decko** [comment]
Tentei reproduzir o BUG alterando a situação do Processo de algum ente federado para "Publicado no DOU", e não consegui. A situação foi alterada e nenhuma exceção foi levantada.

**Comment by decko** [comment]
O erro só ocorria em homologação devido a uma configuração referente aos dominios da aplicação.
Reconfigurei o ambiente, publiquei as novas versões e fiz umas alterações no código. Este bug é corrigido pelo commit https://github.com/culturagovbr/sistema-nacional-cultura/commit/68664fd7603c8e4a9ebd2e4e954f864d086aa1c0
