### ISSUE TITLE
Atualizar o form AlterarSituacao no app de gestão

### ISSUE THREAD

**Issue by matheusbsilva** [culturagovbr/sistema-nacional-cultura#136]
É necessário alterar o comportamento do form ```AlterarSituacao``` presente no app de gestão para se adequar as novas modificações feitas nas models referentes aos componentes do plano de trabalho, onde os fields referentes aos arquivos e situações foram modificados.

**Comment by matheusbsilva** [comment]
É necessário modificar qual field referente a **situação** é inicializado na criação dos componentes que ocorre no form.

**Comment by izacristina** [comment]
@matheusbsilva isso já foi feito?

**Comment by matheusbsilva** [comment]
Resolvido
