### ISSUE TITLE
Situação de cada componente do Plano de Trabalho não é exibido corretamente.

### ISSUE THREAD

**Issue by decko** [culturagovbr/sistema-nacional-cultura#140]
A situação dos arquivos/componentes não está sendo exibida corretamente. Este problema ocorre também com os municípios/estados que já haviam aderido à plataforma.

Suspeitas:
- O sistema não está obtendo a situação a partir da nova estrutura de arquivos do componente.

**Comment by matheusbsilva** [comment]
A situação dos componentes não foi atualizada na migração de dados feita para copiar os arquivos para os novos fileds. O sistema já está implementado observando o novo field referente a situação dos componentes, e como não ocorreu essa migração, todos continuam com o valor default.
