### ISSUE TITLE
Filtrar por data de envio.

### ISSUE THREAD

**Issue by AnaOlivei** [culturagovbr/sistema-nacional-cultura#143]
Verificamos no DAP e um item das consultas avançadas é a visualização filtrada por data de envio do arquivo do Plano de Trabalho. Assim poderemos analisar o arquivo por ordem de chegada.

**Comment by matheusbsilva** [comment]
@AnaOlivei Seria então ordenar a listagem dos entes federados na tela inicial de gestão pela data de envio dos arquivos, quanto mais antigo, mais prioritário?

**Comment by AnaOlivei** [comment]
Exatamente, pois há municípios que enviaram arquivos há muito tempo que não foram analisados ainda.

**Comment by AnaOlivei** [comment]
@matheusbsilva Olá o componente da lei do sistema é o mais importante para ser filtrado.

**Comment by AnaOlivei** [comment]
@izacristina deve ficar primeiro o que precisa avaliar o anexo, porque em preenchimento a pessoa não colocou o documento ainda.

**Comment by matheusbsilva** [comment]
@AnaOlivei outro critério para essa ordenação seria o estado do processo? Ou seja, priorizar quem está com o estado de **Publicado no DOU**, já que não é possível avaliar os componentes do plano de trabalho de entes federados que não se encontram nesse estado do processo. Para evitar que esse tipo de situação aconteça na tela inicial:

![captura de tela de 2018-07-11 13-43-26](https://user-images.githubusercontent.com/14370340/42587545-75f30f16-8511-11e8-9e90-a0e0859af286.png)

**Comment by AnaOlivei** [comment]
@matheusbsilva sim apenas os publicados podem ser analisados, não tinha pensado nisso, pode adicionar mais essa ordem.
