### ISSUE TITLE
Retornar situação e options da Situação Geral do Plano Trabalho - API

### ISSUE THREAD

**Issue by volthier** [culturagovbr/sistema-nacional-cultura#147]
- [ ] Field "situação_geral_plano_trabalho"
- [ ] Retornar options da situação

**Comment by matheusbsilva** [comment]
Atualmente essa informação sobre a situação do plano de trabalho não persiste no banco. Existem duas formas de resolver essa Issue:
1. Persistir a informação do plano de trabalho em um novo field ```situacao``` na model PlanoTrabalho, sendo que essa situação vai ser alterada quando o gestor fizer uma nova diligência geral atribuindo uma nova situação para essa plano trabalho;
2. Inferir a situação do plano de trabalho a partir da situação dos componentes que fazem parte desse plano de trabalho(criacao_sistema, orgao_gestor, plano_cultura, fundo_cultura, conselho_cultural), sendo que ao fazer uma nova diligência geral o gestor será informado sobre a situação do plano trabalho
