### ISSUE TITLE
Filtro Ativo/Inativo (Issue #57)

### ISSUE THREAD

**Issue by volthier** [culturagovbr/sistema-nacional-cultura#152]
Detalhar com o cliente para especificação do filtro e sua necessidade.

**Comment by matheusbsilva** [comment]
@AnaOlivei A situação de ativo/inativo se refere a qual entidade? São os entes federados?

**Comment by AnaOlivei** [comment]
O único local que tem esse filtro se refere aos usuários, na listagem de CPF aparece se ele está ativo ou é um administrador. 
![image](https://user-images.githubusercontent.com/32340472/41163159-4fa80e96-6b0e-11e8-886e-780cb4fdb7fc.png)
