### ISSUE TITLE
Retorno do ID do usuário cadastrador - API

### ISSUE THREAD

**Issue by volthier** [culturagovbr/sistema-nacional-cultura#153]
Retornar junto com a consulta o ID do cadastrador.

**Comment by volthier** [comment]
Retorno necessário na issue #87

**Comment by matheusbsilva** [comment]
A lógica para acessar a tela de gestão de um município com o id do usuário cadastrador não está correta, no processo de refatoração das Models vamos corrigir essa lógica e retornar o id do ente federado, para então acessar corretamente essa tela através do versnc, até lá essa Issue irá permanecer congelada.
