### ISSUE TITLE
Implementar model SistemaCultura para lidar com alteração de cadastradores

### ISSUE THREAD

**Issue by matheusbsilva** [culturagovbr/sistema-nacional-cultura#159]
## Descrição
Implementar versão inicial da model SistemaCultura para lidar com a alteração de cadastradores dos entes federados e guardar um histórico dos cadastradores antigos.

## Tarefas
- [x] Implementar fields:
  - [x]  Uf
  - [x] Cidade
  - [x] Cadastrador
- [X] Implementar lógica para lidar com a alteração dos cadastradores, alterando a referências nas models:
  - [X] Municipio
  - [X] PlanoTrabalho
  - [X] Responsavel
  - [X] Secretario
- [x] Implementar Manager para retornar sempre o sistema de cultura mais atualizado

**Comment by matheusbsilva** [comment]
Lógica para lidar com as entidades relacionadas ao cadastrador foi implementada na model ```SistemaCultura```, mas o testes para os métodos implementados estão falhando por não utilizar a fixture ```plano_trabalho```, ao utilizar a fixture outros testes da aplicação são afetados causando erro. https://github.com/culturagovbr/sistema-nacional-cultura/commit/5b69aecd01dd4ecc9a4e705ef23b2bb2b4f00196

**Comment by decko** [comment]
Corrigido pela 2fe9200.

**Comment by matheusbsilva** [comment]
Foi implementado o Manager `SistemaCulturaManager` que a partir do método `ativo()` filtra o último Sistema Cultura criado identificado pelo campo `data_criacao`. Ex: Para retornar o último Sistema Cultura dado como ativo:
```py
from adesao.models import SistemaCultura

SistemaCultura.objects.ativo()
```
