### ISSUE TITLE
API - Diferenciar estados e municípios

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/sistema-nacional-cultura#165]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Para filtragem das informações no VerSNC ẽ importante saber quem é quem. Atualmente o sistema retorna municípios e estados juntos.

**Qual a proposta de solução?**  
Adicionar duas fields booleanas de pesquisa na API, para retornar somente estados ou somente municípios (e ambos, como já está implementado)

Exemplo: api/sistemadeculturalocal/?municipios=True - Retornaria somente municipios 
 
**Especificação da funcionalidade**  
Novas opções de filtragem na api, por municipio ou estado.

**Comment by luizfpinheiro** [comment]
Quando é feita a filtragem com:

> api/v1/?estadual=true&municipal=true

 a API retorna somente os Estados ao invés de retornar os Municípios e Estados.

**Comment by luizfpinheiro** [comment]
E quando é feita a filtragem com:

> api/v1/?estadual=&municipal=true

 a API retorna somente os Estados ao invés de retornar somente os Municípios.

**Comment by matheusbsilva** [comment]
@luizfpinheiro a primeira situação onde ocorre a filtragem:
> api/v1/?estadual=&municipal=true

Não faz sentido para o modelo de negócio, ou uma adesão é estadual ou ela é municipal, ela não pode ser os dois ao mesmo tempo, mas o comportamento de retornar **somente adesões estaduais** estava **incorreto**, o correto é retornar **vazio**.  Corrigido em 6a142ac547fa95d68508726e02c50cffbee1d635.

Já o segundo caso:
> api/v1/?estadual=&municipal=true

Foi corrigido em 6a142ac547fa95d68508726e02c50cffbee1d635. Agora ao passar um dos parâmetros vazio ele é ignorado.

**Comment by luizfpinheiro** [comment]
@matheusbsilva  Ok!
