### ISSUE TITLE
Criar histórico de arquivos enviados

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#169]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Atualmente quando o arquivo é reprovado ele perde a associação com a adesão e se perde.

**Qual a proposta de solução?**  
É necessária a criação de um histórico para que mesmo que o arquivo seja reprovado seja possível visualizá-lo.

**Especificação da funcionalidade**  
O histórico deverá ficar disponível na tela de gestão.

**Comment by luizfpinheiro** [comment]
Movendo para a sprint seguinte.
