### ISSUE TITLE
Erro ao clicar em alterar cadastrador do estado

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#185]
Na tela de gestão, ao clicar em Alterar Cadastradores e depois em Estado, o seguinte erro ocorre:

![captura de tela de 2018-07-04 10-13-48](https://user-images.githubusercontent.com/14032043/42287590-49ed8362-7f8d-11e8-83d6-dff3e042842e.png)

**Comment by matheusbsilva** [comment]
Erro era causado pois a linha referente a definição do form utilizado na view estava comentada https://github.com/culturagovbr/sistema-nacional-cultura/blob/8790c062855840d1a315eca37dffe4d1546aaabf/gestao/views.py#L90

Aproveitei para implementar o método `save` do form `AlterarCadastradorForm`, pois o form não estava realmente fazendo a alteração do cadastrador. Existe um caso de exceção que não foi tratado ainda, que é quando o ente federado não possui ainda nenhum Sistema Cultura associado a ele.

**Comment by luizfpinheiro** [comment]
@matheusbsilva Movendo issue em andamento para a Sprint 7.

**Comment by matheusbsilva** [comment]
Corrigido o caso de alteração de um cadastrador de um ente federado que não possui Sistema Cultura, mas ainda encontra-se no estado **Work In Progress** pois a solução implementada acaba tornando obrigatória a existência de uma instância da model `Municipio` para o ente federado, ou seja ele deve já ter feito o cadastro no sistema, iniciando o processo de adesão. https://github.com/culturagovbr/sistema-nacional-cultura/commit/b3b6a18b5d7b59f3147b4ac067b3d90f16c715b0
