### ISSUE TITLE
Criar histórico de cadastradores

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#195]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Atualmente não é possível saber quais pessoas já foram cadastradores dos entes federados.

**Qual a proposta de solução?**  
Na área de gestão, criar uma visualização das informações dos cadastradores antigos do ente federado.

**Comment by luizfpinheiro** [comment]
Movendo para a issue seguinte.

**Comment by AnaOlivei** [comment]
@izacristina é bom colocar o nome e o e-mail se possível. :-)
