### ISSUE TITLE
Melhorar o frontend

### ISSUE THREAD

**Issue by diegoaguilera** [culturagovbr/sistema-nacional-cultura#2]
implementar menus e modals

**Comment by diegoaguilera** [comment]
Menu de navegação implementado, faltam algumas melhorias ainda.
O primeiro acesso pode jogar direto para a tela de login, com um link lá para o usuário se cadastrar.

**Comment by uira** [comment]
Sobre a tela de login, @diegoaguilera:
> https://github.com/culturagovbr/sistema-nacional-cultura/issues/4

**Comment by dricaveloso** [comment]
incluir mapa dos municípios que já aderiram, e diminuir pela metade os passos para cadastro!
