### ISSUE TITLE
API - Retornar count de Estados por resultado

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/sistema-nacional-cultura#207]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  

Há somente o retorno da quantidade total de entes federados.

**Qual a proposta de solução?**  

Uma informação 'count_estados' que retorne a quantidade de estados de cada busca que for feita na API.

**Comment by izacristina** [comment]
@AnaOlivei O ente federado é considerado aderido quando a situação da adesão é Publicado no DOU?

**Comment by AnaOlivei** [comment]
@izacristina Sim, só está aderido quando é publicado no DOU.

**Comment by luizfpinheiro** [comment]
Resolvido em #236.
