### ISSUE TITLE
API - Atualizar filtro dos componentes do Sistema em /acoesplanotrabalho

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/sistema-nacional-cultura#209]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Ao pesquisar um Plano Trabalho pelo id da situação do Componente, a API considera o campo de pesquisa como inválido.

**Qual a proposta de solução?**  

Atualizar o acesso as informações dos componentes de acordo com a última alteração nos componentes.

**Especificação da funcionalidade**  
Filtro de pesquisa por situação dos Componentes (id e descrição da situação)

**Comment by matheusbsilva** [comment]
Atualizado em 8d2b77d2998409160009f86506c2f3861bb6c88a
