### ISSUE TITLE
Erro ao tentar acessar os arquivos necessários para efetivar a adesão

### ISSUE THREAD

**Issue by matheusbsilva** [culturagovbr/sistema-nacional-cultura#211]
## Descrição
Ao tentar acessar os arquivos, "Acordo de Cooperação" e "Termo de Solicitação", que o gestor do ente federado deve enviar para efetivar a adesão ocorre um erro.

## Passos que levam ao bug
1. Logar no sistema como usuário comum(cadastrador)
2. Fazer o cadastro de um ente federado
3. Acessar no menu lateral direito a opção "Acordo de Cooperação" ou "Termo de Solicitação"

## Print
![captura de tela de 2018-07-23 10-53-10](https://user-images.githubusercontent.com/14370340/43080617-789df20e-8e66-11e8-85e1-60ba3dac4e9a.png)

**Comment by izacristina** [comment]
No ambiente de homologação, ao tentar acessar essas funcionalidades, o seguinte erro está ocorrendo:

![captura de tela de 2018-08-09 18-12-52](https://user-images.githubusercontent.com/14032043/43930119-2733b880-9c0e-11e8-9392-25c880bbc766.png)

**Comment by izacristina** [comment]
@AnaOlivei O ofício de alteração do responsável também não?

**Comment by AnaOlivei** [comment]
@izacristina o ofício de alteração do responsável continua do mesmo jeito, pois não tem a ver com o SEI.

**Comment by izacristina** [comment]
@AnaOlivei entendi, como chega nessa funcionalidade de gerar o ofício de alteração?

**Comment by AnaOlivei** [comment]
@izacristina Na página inicial, assim que a pessoa se cadastra, aparece a orientação de cadastrar o município ou se já está cadastrado enviar o ofício de alteração clicando nessa mensagem. Dai a plataforma gera um modelo de ofício conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/32340472/44107613-56efade0-9fce-11e8-8ca8-badb3a4965b9.png)

Na imagem abaixo mostra como ele é:

![image](https://user-images.githubusercontent.com/32340472/44107694-a604a4ee-9fce-11e8-9386-51e5233bdac2.png)

**Comment by izacristina** [comment]
@AnaOlivei Muito obrigada <3
