### ISSUE TITLE
Verificar estados ausentes

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#215]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Os seguintes estados não estão na plataforma em produção:
- Amapá
- Alagoas
- Rio grande do sul
- Pernambuco

Verificar o motivo

**Comment by matheusbsilva** [comment]
Rio Grande do Sul está na plataforma:
http://snc.cultura.gov.br/adesao/detalhar/4041

**Comment by PedroMurta** [comment]
Teste
