### ISSUE TITLE
Alteração do Acordo

### ISSUE THREAD

**Issue by AnaOlivei** [culturagovbr/sistema-nacional-cultura#216]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  

Segue em anexo o modelo do novo Acordo de Cooperação que deve ser gerado pela plataforma no momento em que o usuário finalizar o cadastro do município. 
[Acordo de Cooperação - 2018 - SDC.pdf](https://github.com/culturagovbr/sistema-nacional-cultura/files/2227899/Acordo.de.Cooperacao.-.2018.-.SDC.pdf)

O endereço para correspondência agora é :
SCS Qd 09, Lote  C, Ed. Parque Cidade Corporate, Torre B – 10º Andar
CEP 70308-200, Brasília – DF
Deve ser alterado na página inicial onde tem: Equipe SNC conforme imagem abaixo. 
![image](https://user-images.githubusercontent.com/32340472/43201121-f8c7d0a2-8fed-11e8-9a1e-2fb97a822dd0.png)

**Comment by izacristina** [comment]
@AnaOlivei mas essa mensagem com o endereço ainda existe? a gente não tinha trocado para orientar a pessoa a enviar o PDF pro e-mail acordosnc@cultura.gov.br?

**Comment by AnaOlivei** [comment]
@izacristina já? pensei que a gente não tinha trocado ainda essa página, já indicamos para as pessoas acessarem ao SEI então? Se sim, basta alterar o acordo mesmo.

**Comment by izacristina** [comment]
@Matheusss03 A dev foi atualizada, na versão nova nós não usamos mais a wkhtmltopdf porque ela estava dando aquele erro. Como trocamos pra uma nova lib (django-weasyprint) e ela não suporta um HTML para o header separado, eu juntei o header e o template em um só, talvez isso conflite com suas alterações, mas recomendo dar o pull porque aí você vai conseguir testar suas coisas.
