### ISSUE TITLE
Campo de Data no Plano de Trabalho

### ISSUE THREAD

**Issue by AnaOlivei** [culturagovbr/sistema-nacional-cultura#230]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  

É necessário inserir um campo de data de publicação dos componentes no plano de trabalho e alterar o texto explicativo, conforme imagem abaixo: 
![image](https://user-images.githubusercontent.com/32340472/43916838-152cf314-9be5-11e8-9e89-4c648d15645f.png)

Essa alteração deve ocorrer no login do usuário no momento do preenchimento do plano de trabalho. 
Segue abaixo o texto a ser alterado: 
TEXTO PARA INSERIR DATA DA PUBLICAÇÃO DO COMPONENTE NO PLANO DE TRABALHO 
Você está no ambiente do Plano de Trabalho. Nesta fase, é preciso anexar as comprovações de execução de cada um dos componentes do sistema de cultura local (como leis, decretos e demais normativas), bem como a data de publicação de cada uma delas, nos campos específicos disponíveis nesta plataforma.
Tais arquivos serão validados pela equipe do Ministério da Cultura responsável pelo SNC que enviará uma mensagem após conclusão do procedimento, para o e-mail cadastrado pelo ente federado (estado/município). É importante manter suas informações sempre atualizadas.
OBS: Conforme Acordo de Cooperação Federativa assinado, o ente federado compromete-se a cumprir com o Plano de Trabalho em até dois anos contados da data de publicação do referido Acordo no Diário Oficial da União (DOU). Caso o prazo não seja cumprido, é necessário que o ente federado envie um Oficio assinado pelo Governador – Estado ou Prefeito – Município, solicitando prorrogação por mais dois anos para o e-mail snc@cultura.gov.br. Vide tutorial **“Ofício de Prazo do Plano de Trabalho”**
 (colocar hiperlink)
http://www.cultura.gov.br/documents/1440656/0/%255bNOVA+PLATAFORMA%255d+Como+preencher+o+Plano+de+Trabalho+-+atual..pdf/265b3f60-0e0e-4fd2-a813-85bb3790e64b

**Comment by izacristina** [comment]
@AnaOlivei seria na que você falou ou quando seleciona algum componente, como é o do CNPJ?

![Captura de tela de 2018-08-14 19-09-39.png](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/f4d41642-26a7-4435-b032-934d84563b4d)

**Comment by AnaOlivei** [comment]
@izacristina acho que funcionaria bem da mesma forma do CNPJ.

**Comment by izacristina** [comment]
@AnaOlivei Ficou assim (exemplo a seguir para a data de publicação do componente Fundo de Cultura)

[Uploading... Captura de tela de 2018-08-16 11-02-02.png ]

**Comment by izacristina** [comment]
@AnaOlivei Ficou assim (exemplo a seguir com a data de publicação para o componente Fundo de Cultura), certinho?

![Captura de tela de 2018-08-16 11-02-02.png](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/a58969ae-72fd-4f3d-bd7a-59c7aeab1039)

**Comment by izacristina** [comment]
@AnaOlivei outra dúvida, a pessoa pode enviar o arquivo sem colocar a data? ou é pra dar um erro de campo não preenchido?

**Comment by AnaOlivei** [comment]
@izacristina pode colocar o erro, mas tem q ser visível rs

**Comment by izacristina** [comment]
@AnaOlivei

**Comment by izacristina** [comment]
@AnaOlivei tá bom esse tamanho?

![Captura de tela de 2018-08-16 15-41-40.png](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/21851a35-a4db-442a-8311-b074aa11b356)

**Comment by AnaOlivei** [comment]
@izacristina está ótimo :-)
