### ISSUE TITLE
Permitir adicionar arquivos dos Componentes do Sistema p/ Entes Federados sem cadastradores

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/sistema-nacional-cultura#242]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  

Atualmente não é possível adicionar os arquivos referente ao Ente Federado se ele não possuir cadastrador vinculado.

**Qual a proposta de solução?**  

Vincular o cadastro/alteração a um usuario de responsabilidade do MinC.

**Comment by izacristina** [comment]
Uma nova solução foi proposta: colocar o admin como cadastrador na funcionalidade atual que já existe para alteração de cadastradores, e permitir que seja possível ver os dados dos municípios sem cadastradores.
