### ISSUE TITLE
Tratar responsividade da busca avançada

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#245]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  

Em telas muito pequenas, a opção de Fechar Filtros invade a área da tabela .

**Qual a proposta de solução?**  

Tornar a área da busca responsiva.

**Comment by luizfpinheiro** [comment]
Issue reaberta no repositório certo. [#52](https://github.com/culturagovbr/versnc/issues/52)
