### ISSUE TITLE
Adicionar pop-up de confirmação.

### ISSUE THREAD

**Issue by AnaOlivei** [culturagovbr/sistema-nacional-cultura#26]
Ao alterar situações no ambiente de administrador da plataforma é necessário adicionar um pop-up de confirmação.

**Comment by matheusbsilva** [comment]
@AnaOlivei seria somente a situação da adesão?

**Comment by AnaOlivei** [comment]
Não,é na área de alteração do responsável. Toda vez que vamos mudar um responsável temos que conferir se alterou mesmo, pois a página só desaparece. Na adesão aparece a data de publicação então da pra ver que está correto.

**Comment by luizfpinheiro** [comment]
Locais do sistema onde o pop-up de confirmação deve ser adicionado:
- [ ] Alteração de Cadastrador
- [ ] Alteração de Situação da Adesão

**Comment by AnaOlivei** [comment]
@luizfpinheiro exato :-)

**Comment by luizfpinheiro** [comment]
Outras telas para adicionar o popup de confirmação:

- [ ] Inserir Documentos
- [ ] Alterar Prazos
