### ISSUE TITLE
Alterar Prazo - Permanecer na mesma página após adicionar prazo para algum Ente Federado

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/sistema-nacional-cultura#261]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  

Ao adicionar um prazo para um Ente Federado, o sistema retorna para a primeira página de pesquisa (ou recarrega se estiver na primeira)

**Qual a proposta de solução?**  

Permanecer na mesma página que o usuário estava após um prazo ser adicionado.

**Especificação da funcionalidade**  

Tela de Alterar Prazo (somente usuários de Gestão)

**Comment by EzequielDeOliveira** [comment]
@luizfpinheiro  @izacristina  essa issue estava para ser discutida se não me engano, mas por via das duvidas, fiz ela
