### ISSUE TITLE
Trocar comportamento dos botões da diligência

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#282]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  

Atualmente há uma opção positiva e negativa para fazer a diligência. A positiva leva para a tela de adição do texto da diligência com apenas a opção 'Concluída' para classificação do arquivo. A negativa leva para a tela de adição do texto da diligência com as opções 'Arquivo danificado', 'Arquivo incompleto' e 'Arquivo incorreto'.

A proposta é que a opção positiva crie uma diligência com a classificação 'Concluída' direto, e com o texto vazio, sem precisar passar pela tela abaixo:

![Captura de tela de 2018-10-01 16-53-16.png](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/bc7ee33e-56a9-4943-97ac-ac9df6755665)

E a diligência negativa continue como está, passando por essa tela e com as três opções: 'Arquivo danificado', 'Arquivo incompleto' e 'Arquivo incorreto'.

**Comment by izacristina** [comment]
@AnaOlivei vocês estão de acordo com esse comportamento?

**Comment by tonygb** [comment]
Olá, Iza,

Concordo sim. Foi o que acordamos na reunião. A questão é que, além dessa mudança, é necessário que o texto da diligência apareça quando clicamos em "criar diligência", na aba "Situação geral do plano de trabalho".

**Comment by izacristina** [comment]
Foi acordada uma nova abordagem, em que no lugar da opção positiva e negativa foi colocado o texto "Criar Diligência", que leva pra tela de criação da diligência com todas as opções de status. Deve ser permitido que para a situação "Concluída" não seja colocado o texto
