### ISSUE TITLE
Retirar os arquivos "errados" da plataforma

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#31]
SADI passou para nós os arquivos que estão errados.

São arquivos incorretos que os municípios fizeram upload do plano de trabalho, mas que a secretaria gostaria de remover.

Abordagem: Checar a viabilidade e facilidade de se criar um botao delete pro arquivo, caso o time box seja alto ( > 1 dia), não implentar, ao invés disso, criar script para remover a lista de documentos pontualmente.

**Comment by luizfpinheiro** [comment]
A solução escolhida foi montar um script para remover os documentos errados e possibilitar o reenvio pelo gestor.

**Comment by luizfpinheiro** [comment]
Resolvido com sucesso. O script usado "deleta" o arquivo incorreto enviado pelo gestor e atualiza o campo "situação" do documento específico para o status "Arquivo Incorreto", possibilitando o reenvio pelo gestor. Script foi rodado no banco e atualizou os munípios que estavam errados na plataforma.
