### ISSUE TITLE
Incluir no SNC os municípios que não estão aparecendo, porém tem acordo publicado

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#32]
Esses municípios existem na política, mas não estão no sistema.

SADI nos passou a lista de municipios, checar com aval como ele criou municipios sem cadastradores no passado e checar a viabilidade.

**Comment by luizfpinheiro** [comment]
Resolvido em https://github.com/culturagovbr/sistema-nacional-cultura/commit/3e961a16a30833c9fe881d71c454cbd7ba162547

**Comment by chris-redfield** [comment]
Opa, acabamos não se comunicando e o problema foi entendido errado, favor desfazer o merge

**Comment by decko** [comment]
- [ ] Obter a lista de municipios divergentes da base com o reclamado.

**Comment by matheusbsilva** [comment]
- [ ] Incluir munícpios que não existem na plataforma e corrigir os que estão com o nome incorreto
- [ ] Conseguir dados referentes a adesão desses municípios(Pedir para área de negócio)
- [ ] Criar uma adesão para os municípios

**Comment by luizfpinheiro** [comment]
Foi elaborado um script sql para incluir os municípios não existentes na plataforma e atualizar os que estavam incorretos.

**Comment by matheusbsilva** [comment]
Foi criado um script em python para gerar as adesões do municípios que não constavam na plataforma:

**Execução:**
1. Acessar a máquina de produção do SNC
2. Entrar no diretório raiz do projeto
3. Mover o script ``inserir_adesoes.py`` para a pasta raiz do projeto 
4. Ativar o **ambiente virtual** do python
5. Acessar o shell do django pelo o comando:
 ``$ python3 manage.py shell ``
6. Executar o script:
``exec(open('inserir_adesoes.py').read())``
