### ISSUE TITLE
Colocar a API no ambiente de homologação c/ a URI correta "hmg.api.snc.cultura.gov.br" e abrir para acesso externo

### ISSUE THREAD

**Issue by matheusbsilva** [culturagovbr/sistema-nacional-cultura#35]
- [ ] URI hmg.api.snc.cultura.gov.br
- [ ] Abrir para acesso externo
- [ ] Discutir com equipe DEVOPS MinC qual é a abordagem para gestão dos subdomínios

**Comment by matheusbsilva** [comment]
endereço: api.snchomolog.snc.cultra.gov.br

**Comment by chris-redfield** [comment]
Ok rolando local, mas agora precisamos fazer funcionar no apache (env homolog e prod)

**Comment by matheusbsilva** [comment]
Pra testar o funcionamento precisa adicionar o ServerAlias api.snchomolog.cultura.gov.br(no caso do server de homologação) no virtual host do apache e configurar dns

**Comment by decko** [comment]
Conforme conversamos, vamos cancelar o subdominio referente a API e manter ela como uma URL do dominio principal.

No caso de homologação, seria:
```
https://homolog.snc.cultura.gov.br/api/v1/
```

No caso de produção:
```
https://snc.cultura.gov.br/api/v1/
```

**Comment by decko** [comment]
Implementamos o seguinte subdomínio:
```
http://hmg.snc.cultura.gov.br
```
atendendo a um padrão com outras aplicações já em desenvolvimento no MinC.
A API do SNC também já responde ao subdomínio.
