### ISSUE TITLE
ID da Cultura

### ISSUE THREAD

**Issue by uira** [culturagovbr/sistema-nacional-cultura#4]
A idéia é lançar esse cara já com um Provedor de Identidade?

**Comment by avaloni** [comment]
Não nesse primeiro momento

**Comment by diegoaguilera** [comment]
omódulo de login aceita SSO?

**Comment by brunosmartin** [comment]
Bota o django-all-auth aí, que aceita Oauth (SSO), bem como integra com providers já conhecidos (google, facebook, etc) e tem um suporte pra usuários bem massa.

Eu diria que é o projeto (app django) mais maduro relacionado a autenticação e usuário pra django.

**Comment by uira** [comment]
Porque o ticket foi fechado antes de ser implementado?
