### ISSUE TITLE
Criar opção para envio da lei do conselho

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#416]
No módulo de adesão:
- Na opção Plano de Trabalho, criar opção para envio da lei do conselho

No módulo de gestão:
- Atualizar página de detalhe do município para mostrar opção para fazer diligência da lei
- Adicionar opção de inserção deste ente na aba 'Inserir Documentos'
- Adicionar opção de fazer a diligência deste arquivo na aba 'Plano de Trabalho'

**Comment by izacristina** [comment]
@AnaOlivei Atualmente, a tela pra inserção do arquivo do conselho está da seguinte forma:

![image.png](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/6e9b0978-963b-4b61-b487-77f2417b08b1)

Como se já solicitasse a ata, não entendi se o campo atual é a lei e é pra criar um pra ata. Teria como esclarecer?

**Comment by izacristina** [comment]
@AnaOlivei o campo de inserção do arquivo e da data da publicação da lei devem ser obrigatórios para o usuário? e para os gestores?

**Comment by izacristina** [comment]
Ainda falta atualizar as telas para permitir a criação das diligências para o arquivo da lei, as telas de inserção da lei já foram criadas, sendo elas:

### pro gestor

![image.png](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/62a30439-b84f-456f-8361-3defd53e18ec)

### pro usuário

![image.png](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/fa16a66b-4ea9-45cd-84d9-574c9b426a35)

**Comment by izacristina** [comment]
@AnaOlivei No quadro a seguir, qual texto deve aparecer para a lei do conselho? Lei de Regulamentação da Criação do Conselho de Políticas Culturais?

![image.png](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/59e9f3d8-912b-4595-a5f7-938cdee7fdfd)

**Comment by AnaOlivei** [comment]
@izacristina acredito que sim, mas estou de férias é importante perguntar para Verena.
