### ISSUE TITLE
Colocar opção para o gestor informar se o ente participou da conferência nacional

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#433]
No módulo de gestão, adicionar opção para que o gestor informe se o ente participou ou não da conferência nacional.

Essa informação deve ser mostrada na planilha e retornada na API.

**Comment by izacristina** [comment]
@AnaOlivei você sabe informar se será necessário em algum momento inserir algum arquivo de comprovação da conferência (seja estadual ou municipal)?

**Comment by AnaOlivei** [comment]
@izacristina  segundo a Verena: 

Isso não é prioridade agora, mas futuramente, vamos precisar sim.

Primeiro, seria necessário que tivéssemos a confirmação de participação ou não participação dos entes federados nas conferências Nacionais.

Posteriormente, pensamos em transformar a conferência como mais um componente de subir arquivos na plataforma, mas ainda não sabemos como será isso.
