### ISSUE TITLE
Apagar os dados cadastrais do município de Cacimbinhas/AL

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#456]
Os dados foram criados pelos gestores do MinC para teste, é necessário apagá-los.

**Comment by izacristina** [comment]
@AnaOlivei quais dados devem ser removidos?

**Comment by AnaOlivei** [comment]
@izacristina todos os dados devem ser removidos, pois o município não aderiu, tudo o que foi incluído era um teste.
