### ISSUE TITLE
Criar endpoints /conselheiros e /componentes.

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/sistema-nacional-cultura#50]
Serão principais no "ver-SNC":
- Sistema de Cultura Local
- Ações do Plano Trabalho
- Conselheiros
- Componentes

**Comment by chris-redfield** [comment]
Após planejamento da sprint, foi definido que não criaremos esses novos endpoints, somente criaremos filtros com essas entidades (que tem conselho, por exemplo) para filtrar nos endpoints já existentes
