### ISSUE TITLE
Integração com serviço de consulta a CNPJ da receita federal

### ISSUE THREAD

**Issue by avaloni** [culturagovbr/sistema-nacional-cultura#509]
Integrar o SNC com o web service do Ministério para consulta e validação de CNPJs, os CNPJs precisam ter sua existência validada e os dados retornados pela consulta precisam ser apresentados aos gestores do SNC.

Os seguintes CNPJs precisam disso:

- CNPJ do Ente Federado
- CNPJ do Fundo de Cultura

**Comment by gcrivellente** [comment]
Fizemos o teste como usuário e deu erro 500.

**Comment by gcrivellente** [comment]
Foi corrigido??

**Comment by izacristina** [comment]
@gcrivellente sim, é pra estar funcionando em hmg

**Comment by gcrivellente** [comment]
Homologado, pode subir para produção.
