### ISSUE TITLE
Desfazer vinculação errada de entes federados

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#53]
Alguns cadastradores "assumiram" certos entes federados por engano e não conseguem desfazer esse ato. Os gestores do SNC também não conseguem pela plataforma.

**Comment by chris-redfield** [comment]
Além de desefazer a vinculação, é necessário tratar essa questão no negócio / sistema

**Comment by decko** [comment]
- [ ] Obter lista de entes federados com vinculação equivocada.

**Comment by decko** [comment]
É necessário travar a adesão dos estados q já estão aderidos.
Santa Maria da Boa Vista - PE, está aderido como Estado.

**Comment by matheusbsilva** [comment]
Elaboramos um script python que vincula o estado de PE a cidade de Santa Maria da Boa Vista, e deleta o estado de SP com dados errados.

**Comment by chris-redfield** [comment]
Pedimos um novo teste para a área de negócio, última tentativa deles, o responsável por são paulo não estava aparecendo
