### ISSUE TITLE
Refazer o fluxo de inserção do conselho de cultura

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#538]
Permitir que o usuário:

- Copie a lei do sistema caso seja igual
- Faça upload da ata
- Informe se é exclusivo da cultura
- Informe se é paritário

Conforme fluxo da imagem abaixo

![photo5048915399013410843.jpg](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/2f71543b-c794-42d7-ace6-a9ce3fbe9a57)

**Comment by gcrivellente** [comment]
Fizemos o teste e deu erro 500. Selecionamos que é a mesma lei do sistema, que tem ata e que é paritário.

**Comment by gcrivellente** [comment]
Fiz o teste e deu certo. Pode subir para produção.
