### ISSUE TITLE
Refazer o fluxo de inserção do plano de cultura

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#539]
Permitir que o usuário:
- Faça upload de um anexo
- Faça upload das metas
- Informe se o plano é exclusivo da cultura 
- Infome último ano de vigência
- Informe periodicidade
- Informe local de acompanhamento dos resultados do monitoramento do plano
- Informe participação em algum Programa de Formação de Gestor e Conselheiros Culturas (informando esfera da federação, ano e tipo)

Conforme fluxo das imagens abaixo:

![photo5048915399013410842.jpg](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/5af0c0d9-b2f8-48a2-a864-d65367ee9bf9)

![photo5048915399013410841.jpg](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/80bccd32-a9f0-4a54-872e-520a76f7d56a)

**Comment by Ana1603** [comment]
Testado e homologado.
