### ISSUE TITLE
 Consultas divergentes na plataforma

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#54]
Investigar casos em que os municípios aparecem e depois não aparecem na plataforma

**Comment by chris-redfield** [comment]
- [ ] Obter listas divergentes
- [ ]

**Comment by Matheusss03** [comment]
Na página inicial de gestão, deveria ser mostrado todos os municípios cadastrados, sem filtro algum. Porém há uma filtragem de todos as situações existentes, menos a situação **Publicado no DOU**.
Logo, quando faz a filtragem pela situação **Publicado no DOU** há mais registros que na página inicial.

**Comment by chris-redfield** [comment]
Feedback da SADI: Trazer os entes federados de TODOS os estados de adesão, inclusive "Publicado no DOU"

**Comment by Matheusss03** [comment]
Análise dos entes federados presentes na tela de gestão e suas respectivas situações processuais

Obs:
 - *Download*: Quantidade de elementos quando exportamos uma planilha
 - *Gestão*: Quantidade de elementos que podem ser vistos na tela de gestão
 - *Correta*: Quantidade de elementos após inserção das atualizações

![Tabela](https://raw.githubusercontent.com/wiki/culturagovbr/sistema-nacional-cultura/images/tabela.jpg)
