### ISSUE TITLE
Mudar componentes 'em preenchimento' para 'avaliando anexo'

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#540]
Mudar componentes cujos arquivos estão com situação 0 (Em preenchimento) para 1 (Avaliando Anexo), caso estes componentes possuam arquivo

**Comment by verenasantiago** [comment]
Ainda não solucionado. Continua "em preenchimento"
![image](https://user-images.githubusercontent.com/20840454/58658884-f3c7c780-82f7-11e9-8410-7237fa399b44.png)

**Comment by izacristina** [comment]
@verenasantiago esse 'em preenchimento' aí é apenas uma das opções de situação, é só clicar na opção que abrem todas e vocês selecionam a que vocês querem.

Na imagem abaixo por exemplo, eu selecionei 'arquivo danificado' e salvei tranquilamente

![Captura de tela de 2019-05-30 18-23-05](https://user-images.githubusercontent.com/14032043/58665893-45784e00-8308-11e9-8d33-f4bfc7d1f662.png)

**Comment by gcrivellente** [comment]
Tinha pedido para mudar o texto "em preenchimento" para "situação do arquivo" (não lembro se era esse o nome)

**Comment by gcrivellente** [comment]
Ainda está aparecendo o texto "em preenchimento", tínhamos pedido para colocar "avaliando anexo"
