### ISSUE TITLE
Reestruturação tela Plano de Trabalho

### ISSUE THREAD

**Issue by ShinNin-chan** [culturagovbr/sistema-nacional-cultura#542]
No perfil de usuário, na tela Plano de Trabalho faltam botões para enviar comprovante nas opções a) e b) do segundo tópico. Também é necessária a remoção dos tópicos e simplificação da leitura da sequencia de itens. Como apresentada na figura de exemplo abaixo.![Group 3.png](https://images.zenhubusercontent.com/5a5769664b5806bc2bc25a52/e0e26969-5fee-451c-a41b-7fb9b1e226c8)

**Comment by izacristina** [comment]
pessoal, não entendi sobre as opções a) e b), é para removê-las?

**Comment by Ana1603** [comment]
Testado e homologado.
