### ISSUE TITLE
Recuperar data de envio dos componentes no servico de arquivos

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#56]
Para ordenação da análise do plano de trabalho será necessário armazenar a data de envio, avaliar se é viável recuperar isso do sistema de arquivos e implementar dentro dessa sprint

**Comment by matheusbsilva** [comment]
@decko qual tinha sida a sua proposta de solução para isso?

**Comment by decko** [comment]
@matheusbsilva Utilizar a ultima modificação do conteúdo do arquivo como data de recebimento. Dá pra usar o os.stat() para obter essa informação. Estou assumindo esta issue para tratar esse assunto.
