### ISSUE TITLE
Criar opção para registro de contato com o ente

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#561]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**  
Quando a equipe do SNC entra em contato com algum ente federado, eles não possuem um lugar na plataforma para registrar o que foi discutido neste diálogo.

**Qual a proposta de solução?**  
Criar um formulário no módulo de gestão no qual o gestor possa informar:
- Com quem ele falou
- Qual foi a data do contato
- O que foi discutido (texto aberto)
Além disso, deve-se registrar o gestor logado como quem fez o contato.

É importante que seja possível ver na página do ente (no módulo de gestão), o histórico de contatos realizados.

**Comment by verenasantiago** [comment]
Testado e está ok.
