### ISSUE TITLE
Correção de links Publicado no DOU e "Nome do Ente" [USR]

### ISSUE THREAD

**Issue by ShinNin-chan** [culturagovbr/sistema-nacional-cultura#567]
O Link que do nome do ente não está redirecionando para a página do Ente Federado;
O Link Publicado no DOU não redireciona para a publicação.
![image](https://user-images.githubusercontent.com/14078108/57802207-d86f9080-772b-11e9-8ee4-dc6f92735c95.png)

**Comment by Ana1603** [comment]
Correção de links Publicado no DOU - CORRIGIDO
"Nome do Ente" - NÃO VAI PARA A PÁGINA DO ENTE NO VER SNC, e quando vai no versnc e clica em mais informações dá "Página não encontrada".

![image](https://user-images.githubusercontent.com/51002176/58706069-659b2200-8387-11e9-952b-b7b5094a1049.png)
![image](https://user-images.githubusercontent.com/51002176/58706120-819ec380-8387-11e9-9caa-491d917d8d9a.png)

**Comment by Pedro-Philipe** [comment]
@Ana1603 o link do versnc foi estado no ambiente de homologação?

**Comment by Ana1603** [comment]
@Pedro-Philipe agora está ok! Mas antes não estava entrando.
