### ISSUE TITLE
Erro 500 ao clicar em salvar qualquer arquivo inserido no Plano de Trabalho [ADM]

### ISSUE THREAD

**Issue by ShinNin-chan** [culturagovbr/sistema-nacional-cultura#568]
No perfil administrador ao inserir qualquer arquivo em Plano de Trabalho acontece o erro 500.

**Comment by izacristina** [comment]
Corrigido, era apenas problema no servidor. Não relacionado a aplicação.

**Comment by clebersantos** [comment]
@izacristina Homologado. Pode subir para produção.

**Comment by verenasantiago** [comment]
Ok
