### ISSUE TITLE
Botão "escolher arquivo" do campo termo de posse nas telas Criar Ente e Alterar Ente Desapareceu. [USR]

### ISSUE THREAD

**Issue by ShinNin-chan** [culturagovbr/sistema-nacional-cultura#577]
![image 16](https://user-images.githubusercontent.com/14078108/58287149-b490f800-7d86-11e9-9ccc-0bc6af03c9a0.png)

**Comment by verenasantiago** [comment]
Botão de inserir arquivo do Termo de Posse está aparecendo agora. ok.

**Comment by ShinNin-chan** [comment]
@verenasantiago Apareceu pra mim ontem também. Ficou perfeito.
