### ISSUE TITLE
Erro "Data inválida" ao inserir componente do Plano de Trabalho. [ADM]

### ISSUE THREAD

**Issue by ShinNin-chan** [culturagovbr/sistema-nacional-cultura#578]
Na hora de selecionar uma data, o formato de display  não está DD/MM/AAAA e sim MM/DD/AAAA. Só que na hora de validar esse formato de display, os dias que são maiores que 12 são considerados data inválida.
Segue uma imagem:
![image](https://user-images.githubusercontent.com/14078108/58288069-f15dee80-7d88-11e9-9f4e-5f58b9ffcae8.png)

**Comment by verenasantiago** [comment]
Testado no homolog e está ok.
