### ISSUE TITLE
Situação do usuário ativo/inativo não fica salva [ADM]

### ISSUE THREAD

**Issue by ShinNin-chan** [culturagovbr/sistema-nacional-cultura#581]
Na página de usuários a situação de ativa ou inativa não permanece salva. Além disso as opções para ativar ou inativar o cadastro estão invertidas.
![Captura de tela de 2019-05-30 14-31-40](https://user-images.githubusercontent.com/14078108/58651879-bc055380-82e8-11e9-91bd-473ab3c18e30.png)
![Captura de tela de 2019-05-30 14-31-45](https://user-images.githubusercontent.com/14078108/58651880-bc055380-82e8-11e9-8a62-b54d47a91e24.png)

**Comment by verenasantiago** [comment]
Não está sendo possível colocar o usuário como ativo. Não salva e ele continua como inativo

**Comment by Pedro-Philipe** [comment]
@verenasantiago Já estou analisando essa issue

**Comment by verenasantiago** [comment]
Bom dia!!! Agora está certo! Assim, vamos iniciar os testes no perfil de usuário no homolog. Obrigada.
