### ISSUE TITLE
Inserir situação do ente federado no adm

### ISSUE THREAD

**Issue by verenasantiago** [culturagovbr/sistema-nacional-cultura#587]

**Comment by verenasantiago** [comment]
Quando clicamos no ente federado para ver seus dados, não tem nenhum campo com a situação cadastral do ente. 
![image](https://user-images.githubusercontent.com/20840454/59038892-20c13080-884a-11e9-8213-3e309acaab34.png)

Somente se clicamos para alterar a adesão
![image](https://user-images.githubusercontent.com/20840454/59038963-464e3a00-884a-11e9-8786-e3da73591f50.png)

Ou na pesquisa de entes federados
![image](https://user-images.githubusercontent.com/20840454/59038757-f1122880-8849-11e9-8398-f4a1738f3f18.png)

**Comment by verenasantiago** [comment]
Sugestão:
Pode ser inserido no quadro vermelho ou melhor distribuída as informações no quadro do ente federado
![image](https://user-images.githubusercontent.com/20840454/59039154-a8a73a80-884a-11e9-99dd-9fdaceaafd31.png)

**Comment by Ana1603** [comment]
Testado e homologado.
