### ISSUE TITLE
Adicionar automaticamente barras ao inserir a data de publicação no Plano de trabalho [ADM]

### ISSUE THREAD

**Issue by Ana1603** [culturagovbr/sistema-nacional-cultura#588]
Quando vai inserir o arquivo no componente no plano de trabalho e pede para colocar a data, toda vez tem que adicionar a barra pra separar dia/mês/ano, ela não vai automaticamente. Não sendo possível salvar o arquivo.

![image](https://user-images.githubusercontent.com/51002176/59050876-e06dac80-8861-11e9-89f2-d9f5fb3d3fad.png)

**Comment by gcrivellente** [comment]
Testado e homologado. Pode subir para produção.
