### ISSUE TITLE
Estado aparecer como primeiro da lista na pesquisa ADM

### ISSUE THREAD

**Issue by verenasantiago** [culturagovbr/sistema-nacional-cultura#589]
Ao inserir o nome para pesquisar o ente federado, os Estados aparecem como último na lista. O certo é deixá-los como primeiro da lista.
![image](https://user-images.githubusercontent.com/20840454/59060083-ab1f8980-8876-11e9-8fea-cdd86cf91700.png)

**Comment by Pedro-Philipe** [comment]
@verenasantiago Essa issue é realmente necessária? Pois é possível alterar a ordenação das colunas clicando no título delas. As colunas não são mais estáticas. Aguardo resposta.

**Comment by izacristina** [comment]
Colocar botão de filtro para município ou estado

**Comment by gcrivellente** [comment]
Homologado, pode subir para produção.
