### ISSUE TITLE
Dentro do componente conselho é necessário alterar "arquivo do componente" para "arquivo ata" - ADM

### ISSUE THREAD

**Issue by gcrivellente** [culturagovbr/sistema-nacional-cultura#591]
Quando põe para editar o componente do conselho, aparecem as opções de inserir os dois arquivos (ata e lei).

Na parte da ata é necessário substituir o título para "Arquivo - Ata", para que se possa diferenciar os documentos que estão sendo inseridos
![conselho](https://user-images.githubusercontent.com/50843971/59070464-2c841580-8891-11e9-9731-84e70261f1ca.png)

**Comment by Pedro-Philipe** [comment]
#600
