### ISSUE TITLE
Inserir botão de voltar quando acessar documentos do prefeito/governador - ADM

### ISSUE THREAD

**Issue by gcrivellente** [culturagovbr/sistema-nacional-cultura#599]
Quando clicamos no nome do prefeito, abre o documento de posse dele. Contudo, não tem o botão para retornar à página anterior (que aparece a pesquisa dele).
A opção que ele dá é clicar no botão de retornar do próprio browser, e neste caso tem que refazer a consulta do ente federado.

![imagem 01](https://user-images.githubusercontent.com/50843971/59198453-2aa8a380-8b6a-11e9-8f85-ad3dd5009c49.png)
![imagem 02](https://user-images.githubusercontent.com/50843971/59198454-2aa8a380-8b6a-11e9-948f-7808b1559eb4.png)

**Comment by gcrivellente** [comment]
Não está aparecendo o botão de voltar. Desta forma, não tem como homologar

**Comment by Pedro-Philipe** [comment]
Não é possível inserir um botão de voltar, quando clica no link o navegador (chrome) faz o download do arquivo que foi baixado e já abre automaticamente na mesma aba, eu coloquei para ele abrir em outra aba. É o que é possível ser feito.

**Comment by izacristina** [comment]
Colocar para abrir em uma nova página em todos os links de arquivo

**Comment by Ana1603** [comment]
Testado e homologado.
