### ISSUE TITLE
Colocar título no nome do componente do órgão gestor - ADM

### ISSUE THREAD

**Issue by gcrivellente** [culturagovbr/sistema-nacional-cultura#601]
Quando clica para inserir ou avaliar o órgão gestor de cultura, não aparece o nome desse componente. Fica apenas "avaliar componente". No caso, deverá ser "Avaliar órgão gestor de cultura". 
![imagem 04](https://user-images.githubusercontent.com/50843971/59200166-00f17b80-8b6e-11e9-9fd2-5a9ee864508a.png)

**Comment by izacristina** [comment]
Duplicada #600
