### ISSUE TITLE
Não aparece a opção de subir a ata do conselho - ADM

### ISSUE THREAD

**Issue by gcrivellente** [culturagovbr/sistema-nacional-cultura#602]
O município (Palmas/TO) tem a lei do conselho, porém, ao clicar em inserir componente, não aparece a opção de inserir a ata do conselho.

![imagem 05](https://user-images.githubusercontent.com/50843971/59200294-48780780-8b6e-11e9-9aa6-b5518646848b.png)

**Comment by Pedro-Philipe** [comment]
@gcrivellente Os que são especializados eu poderia colocar algo tipo Conselho (Lei/Ata), que são o mesmo formulário?
