### ISSUE TITLE
Reorganizar e inserir informações do ente federado - ADM

### ISSUE THREAD

**Issue by gcrivellente** [culturagovbr/sistema-nacional-cultura#606]
Para facilitar a visualização, sugerimos reorganizar as informações dentro do box do ente federado. Exemplo: Lucena/PB. Acredito que pode deixar à esquerda as informações de contato do prefeito/prefeitura (email, endereço e telefone) e à direita as informações "administrativas" da prefeitura. 
É necessário inserir o campo do "CEP" e se há site 

**Lado esquerdo:**
Localização
CNPJ
Prefeito
CPF
RG
E-mail institucional:
E-mail pessoal:
Telefone:
Endereço:
Complemento:
CEP:
Sítio institucional:

**Lado direito:**
Processo SEI
Publicação no DOU
Participou da Conferência Nacional de Cultura:
Última atualização:
Atualizado pelo usuário de CPF:

![imagem 09](https://user-images.githubusercontent.com/50843971/59203866-d4d9f880-8b75-11e9-8b3a-18e6b41fa7b5.png)

**Comment by izacristina** [comment]
O sítio institucional é o endereço eletrônico

**Comment by Ana1603** [comment]
Testado e homologado.
