### ISSUE TITLE
Alguns municípios não estão aparecendo a data de adesão - ADM

### ISSUE THREAD

**Issue by gcrivellente** [culturagovbr/sistema-nacional-cultura#609]
Exemplo do município de Rolim de Moura/RO, ele aderiu no dia 22/01/2013, porém, na parte de pesquisa por ente federado, não aparece a data de adesão dele. 
![imagem 13](https://user-images.githubusercontent.com/50843971/59217393-3ad57880-8b94-11e9-83ba-a197226bacba.png)

**Comment by Pedro-Philipe** [comment]
@gcrivellente Poderia tentar apertar Ctrl + f5 ou Ctrl + R ou Ctrl + shift + R. Acabei de testar em produção e está aparecendo normalmente:![Screenshot from 2019-06-12 15-20-40.png](https://images.zenhubusercontent.com/5a58ea374b5806bc2bc288bf/3ad511ee-03b6-4e4e-b9b5-e107545ee4e3)

**Comment by gcrivellente** [comment]
Testei aqui,  deu certo.
