### ISSUE TITLE
Permitir submissao de componentes antes da adesao

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#61]
Disponibilizar ao ente federado a possibilidade de inserção de documentos paralelamente ao
processo de adesão
- [ ] reproduzir o processo de adesao e submissao
- [ ] implementar a melhoria
- [ ] testar extensivamente

**Comment by matheusbsilva** [comment]
@chris-redfield Qual a necessidade de subir arquivos paralelamente ao processo de adesão, e quais arquivos são esses?

**Comment by chris-redfield** [comment]
Opa, anotei essa necessidade faz um tempasso e acho difícil lembrar com precisão. A área de negócio pediu isso pois os entes só podiam subir esses documentos após a adesão, e isso estava burocratizando o processo. Por alto é isso, mas sugiro fortemente questionar se ainda é necessário fazer isso, e qual a prioridade. 

Abs!
