### ISSUE TITLE
diligência para caixa de e-mail do SNC

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#62]
Enviar copia do e-mail de diligência para uma caixa de e-mail do SNC, para poder ser
pesquisada pela equipe.

Avaliar se essa é a melhor solução.

**Comment by matheusbsilva** [comment]
As diligências persistem no banco da aplicação, sendo que não é necessário mais enviar email com a cópia das diligências.
