### ISSUE TITLE
Corrigir filtro de ente federado no canto superior

### ISSUE THREAD

**Issue by Pedro-Philipe** [culturagovbr/sistema-nacional-cultura#620]

**Comment by Ana1603** [comment]
Continua a mesma coisa.

![image.png](https://images.zenhubusercontent.com/5ce846a97744ea153d5d4fc3/81d0b9ad-3647-4ae5-9ee8-72071ca2152b)

**Comment by izacristina** [comment]
Isso é a barra de pesquisa lá em cima, essa aqui:

![image.png](https://images.zenhubusercontent.com/57e7c5fc95e42b6c5ba967b9/59e4568f-3749-4c3e-8bd5-3525f68718de)

**Comment by gcrivellente** [comment]
Funcionou. Homologado. Pode colocar na produção!
