### ISSUE TITLE
Sinalização de componente concluído para o cadastrador

### ISSUE THREAD

**Issue by Pedro-Philipe** [culturagovbr/sistema-nacional-cultura#625]

**Comment by Ana1603** [comment]
Prezados,

Verifiquei no homolog que ainda não está aparecendo a situação do plano de trabalho no usuário, ele sumiu, já no ADM, está ok.

![image](https://user-images.githubusercontent.com/51002176/60277375-cc065800-98d3-11e9-867b-9087dc132069.png)

![image](https://user-images.githubusercontent.com/51002176/60277477-fbb56000-98d3-11e9-9a11-e5550c11e8d1.png)

**Comment by izacristina** [comment]
É pra permitir o reenvio quando é 'Aprovado com ressalvas' ou ele também fica como 'Concluído'?

**Comment by gcrivellente** [comment]
Acho que a questão dessa issue é que para o cadastrador não aparece nenhuma sinalização, por exemplo, o componente "lei do sistema" foi concluído, para ele aparece em branco. Então teria que deixar para ele essa sinalização.
Quanto aos aprovados com ressalvas, nós consideramos como "concluído", porém, é necessário deixar uma opção que ele possa inserir algum complemento do arquivo dele.

**Comment by izacristina** [comment]
Então pro caso do 'Aprovado com ressalvas' vou deixar como está, que aí mostra a situação e permite que o ente edite o componente.

Atualmente mostra como 'Concluída' quando a Lei do componente é avaliada como 'Concluída', e não permite mais a edição do componente, é pra continuar assim? Porque nesse caso, se o ente subir a lei e ela for avaliada como 'Concluída', ele não conseguirá subir outros arquivos do componente depois, pros que tem mais que um.

**Comment by Ana1603** [comment]
Iza acredito que quando o arquivo ta avaliado como concluído, depois de avaliado não poderá ser possível a troca, pra não ter que avaliar novamente.
"Então pro caso do 'Aprovado com ressalvas' vou deixar como está, que aí mostra a situação e permite que o ente edite o componente." Eu creio que é pra deixar assim mesmo.

**Comment by izacristina** [comment]
Pessoal, confere por favor se assim fica ok pra vocês:

**Situação 1** - O ente não enviou nenhum dos arquivos do componente:
![Screenshot-2019-7-5 Sistema Nacional de Cultura(1)](https://user-images.githubusercontent.com/14032043/60735377-78c28400-9f29-11e9-8e96-327225090f8f.png)

**Situação 2** - O ente enviou somente um dos arquivos do componente:

_Obs: No exemplo em questão, ele enviou só a lei, logo ela fica 'avaliando anexo', e a ata fica 'em preechimento'. Como ele ainda pode editar o componente e inserir a ata, fica o botão 'Editar Componente' disponível._

![Screenshot-2019-7-5 Sistema Nacional de Cultura(2)](https://user-images.githubusercontent.com/14032043/60735386-80822880-9f29-11e9-9728-b1eaca1369c4.png)

**Situação 3** - Todos os arquivos do componente foram avaliados como concluídos, então ele não pode mais editar.

![Screenshot-2019-7-5 Sistema Nacional de Cultura](https://user-images.githubusercontent.com/14032043/60735380-7ceea180-9f29-11e9-9ff5-f25f280c8734.png)

**Comment by Ana1603** [comment]
Achei legal.

**Comment by izacristina** [comment]
E a data de publicação das leis? Podem ser editadas depois que a lei é avaliada como 'Concluída'?

**Comment by gcrivellente** [comment]
Por enquanto (até colocar a possibilidade de ele inserir novo arquivo com a justificativa), a data fica fechada junto com a lei do arquivo.

**Comment by ShinNin-chan** [comment]
@izacristina, fiz testes em todos os campos de um município que não tinha incluído nem um documento. Toda vez que inclui um arquivo, o sistema de status funcionou direitinho, menos na quinta opções, Plano de cultura. 
![image 8.2.png](https://images.zenhubusercontent.com/5a5769664b5806bc2bc25a52/267d1a21-ece2-489b-a079-a1e836329d28)

Em um primeiro momento deu um erro 500 na hora de salva. Voltei lá e fui incluindo vários arquivos na opções nessa segunda vez deu certo. Tentei replicar o erro de novo, mas não consegui.

**Comment by izacristina** [comment]
O erro era quando deixava o arquivo da lei e/ou a data vazios, acredito que foi corrigido, pode conferir por favor?

**Comment by ShinNin-chan** [comment]
Testado e homologado.
