### ISSUE TITLE
Exportação de planilha deve considerar aprovados e aprovados com ressalva como concluidos

### ISSUE THREAD

**Issue by Pedro-Philipe** [culturagovbr/sistema-nacional-cultura#626]

**Comment by izacristina** [comment]
@gcrivellente Estou com uma dúvida nessa issue. O que a planilha faz é apenas pegar a descrição da diligência, se foi 'Concluído', aparecerá 'Concluído', se foi 'Aprovado com ressalvas', assim aparecerá.

Seria então pra fazer com que os arquivos com diligência 'Aprovado com ressalvas' apareçam como 'Concluído'?

**Comment by gcrivellente** [comment]
@izacristina Isso mesmo. Os aprovados com ressalvas precisam ser contabilizados como concluídos

**Comment by Ana1603** [comment]
Testado e homologado.
