### ISSUE TITLE
Filtro na plataforma de municípios com adesão está divergente ADM

### ISSUE THREAD

**Issue by gcrivellente** [culturagovbr/sistema-nacional-cultura#633]
Quando selecionamos os municípios com publicação no DOU, aparece o resultado de 2.728. Porém, hoje, existem 2.562 municípios com adesão.
![Screenshot](https://user-images.githubusercontent.com/50843971/59536816-30381d80-8ecb-11e9-867e-be31d90a6106.png)

**Comment by izacristina** [comment]
@gcrivellente Eu olhei em produção e nesse filtro há 2.678 registros, que é o mesmo valor de  municípios + estados no VerSNC em produção. Este valor está incorreto?

**Comment by Ana1603** [comment]
iza esse valor está correto, 2652 municípios com adesão + 26 estados com adesão.

**Comment by Ana1603** [comment]
Isso também ocorre na planilha. Quando filtramos em ordem alfabética os municípios da 2669 municípios com adesão sem os Estados.

![image](https://user-images.githubusercontent.com/51002176/60286493-07118700-98e6-11e9-9edf-3963ad06680f.png)

E quando filtramos em ordem alfabética as siglas dos Estados da 2678, sem os Estados também.

![image](https://user-images.githubusercontent.com/51002176/60286572-32947180-98e6-11e9-9070-47426ad85b67.png)

**Comment by izacristina** [comment]
@Ana1603 Na planilha não mostram só os publicados no DOU, por isso te mais. Seria pra mostrar só os publicados no DOU?

**Comment by Ana1603** [comment]
Sim, pq quando eu coloco lá no filtro publicados no DOU, somente os municípios ele dá mais e é pra da só 2.652

**Comment by izacristina** [comment]
Fechada pois não havia divergência, só não estava sendo selecionada a opção de exportar todos os entes.
