### ISSUE TITLE
Tirar situações que não são utilizadas para o ente federado ADM

### ISSUE THREAD

**Issue by verenasantiago** [culturagovbr/sistema-nacional-cultura#636]
Tirar as seguintes situações dos entes federados que não utilizadas:
- Documentação Recebida - Aguarda Análise;
- Encaminhado para assinatura do secretário SAI;
- Aguarda Publicação no DOU.

![Imagem1](https://user-images.githubusercontent.com/20840454/59688517-3ae90000-91b4-11e9-819e-fd7dce5006c5.png)

**Comment by izacristina** [comment]
O mesmo problema da #612
