### ISSUE TITLE
URGENTE - Problema no fluxograma do conselho (para inserir legislação) na parte do Administrador

### ISSUE THREAD

**Issue by gcrivellente** [culturagovbr/sistema-nacional-cultura#650]
Fui inserir a lei do conselho, perfil administrador, e ele apareceu vários erros, entre eles a exigência de subir a ata do conselho (que tínhamos tirado essa exigência da obrigatoriedade de inserir a ata). O problema é que ele está cobrando alguns campos que para o administrador não aparecem, por exemplo, se o conselho é paritário, se é exclusivo de cultura...O novo fluxo (assim como aconteceu com o órgão gestor) só entrou para o perfil de usuário. 
Assim, o erro aparece quando, ao inserir, o sistema pede para marcar esses campos que não aparecem para selecionar.
![erro componente do conselho](https://user-images.githubusercontent.com/50843971/60063872-d73f6500-96d4-11e9-84b6-4bf477f4488c.png)

**Comment by Ana1603** [comment]
Quando coloco que tenho só a lei, insiro o documento e a data, e não tenho a Ata, ele fala que é obrigatório eu inserir a lei e a data, mas já foi inserida.

![image.png](https://images.zenhubusercontent.com/5ce846a97744ea153d5d4fc3/912bf711-d122-4862-87ca-d8c1e6733172)

Quando insiro todas as informações salva.

Quando digo que é a mesma lei do sistema e digo que não tem Ata também salva. Ou seja, quando eu digo que só tem a lei só salva se tiver a Ata obrigatoriamente.

**Comment by izacristina** [comment]
Por favor, testar se foi corrigido

**Comment by Ana1603** [comment]
Testado e homologado.
