### ISSUE TITLE
Validar se o CNPJ do fundo é igual ao da prefeitura ou estado

### ISSUE THREAD

**Issue by izacristina** [culturagovbr/sistema-nacional-cultura#653]
Caso o usuário informe o CNPJ do ente no cadastro do fundo, mostrar mensagem de erro "CNPJ já cadastrado em seu ente, insira um CNPJ exclusivo do fundo de cultura"

Colocar texto no quadro azul do fundo explicando que o CNPJ do cadastro é o do Fundo Cultural, não do ente federado.

**Comment by verenasantiago** [comment]
INCLUSÃO DE TEXTO NO QUADRO AZUL DO FUNDO (ANTES DO CAMPO DA OBSERVAÇÃO):
- O CNPJ do Fundo de Cultura deve ser matriz e exclusivo para a cultura
- O número do CNPJ do Fundo de Cultura deve ser diferente do CNPJ do estado/DF/município
![image](https://user-images.githubusercontent.com/20840454/60285952-180dc880-98e5-11e9-9515-6d8152507a3b.png)

**Comment by Ana1603** [comment]
Testado e homologado.
