### ISSUE TITLE
Município de Ibiapina/CE está dando erro 500 quando envia para diligência

### ISSUE THREAD

**Issue by gcrivellente** [culturagovbr/sistema-nacional-cultura#683]
O município de Ibiapina/CE está dando erro 500 após fazermos as análises dos documentos enviamos a diligência final para o municípios.

**Comment by ShinNin-chan** [comment]
Nova Olinda/CE também apresentou o mesmo erro. Outro teste foi feito em Nova Olinda/PB para verificar se o erro não era geral. Nesse município de controle o erro não ocorreu.
