### ISSUE TITLE
Automatizar a instalação das bibliotecas pelo pipenv

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/sistema-nacional-cultura#71]
Atualmente há uma branch utilizando o pipenv, mas nem todas as bibliotecas são instaladas automaticamente pelo pipenv, especialmente a biblioteca 'drf-hal-json' que é externa. 
Há a possibilidade de instalar separadamente, mas o ideal é o pipenv conseguir instalar tudo.

**Comment by decko** [comment]
Resolvido pela #91
