### ISSUE TITLE
usar o django localflavor para validar CPF e CNPJ

### ISSUE THREAD

**Issue by brunosmartin** [culturagovbr/sistema-nacional-cultura#8]
Evita dores de cabeça futura, falo por exepriência própria.
https://pypi.python.org/pypi/django-localflavor-br/1.0

**Comment by avaloni** [comment]
Tem algum problema em usar a versão 1.1? https://pypi.python.org/pypi/django-localflavor

Nesse link que você passou menciona que a 1.0 está obsoleta.
