### ISSUE TITLE
Card com nome duvidoso "SMC"

### ISSUE THREAD

**Issue by Matheusss03** [culturagovbr/sistema-nacional-cultura#81]
SMC existe mesmo (Sistema Municipal de Cultura) ou é um erro?

<img src="https://raw.githubusercontent.com/wiki/culturagovbr/sistema-nacional-cultura/images/SMC.png">

**Comment by decko** [comment]
O que a documentação do SNC diz?

**Comment by matheusbsilva** [comment]
@AnaOlivei é pra ser SMC mesmo? :thinking:

**Comment by AnaOlivei** [comment]
@matheusbsilva Sim, pois existe o SNC de Sistema Nacional de Cultura e o SMC de Sistema Municipal de Cultura, cada município deve ter o seu. Mas colocamos Lei do Sistema de Cultura, porque os Estados também tem que inserir esse documento e não queríamos especificar, não sei porque está SMC pode alterar para: "Estruturação do Sistema de Cultura".
