### ISSUE TITLE
Visualizar os dados principais de todas as adesões em formato tabular

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#83]
Eu como gestor do MinC quero visualizar todos os registros de adesão para poder navegar.

**Critérios de Aceitação:**
- [ ] Testes para cada camada envolvida
- [x] Tabela
- [x] Colunas da Tabela
   - [x] Cidade/UF
   - [x] Situação da Adesão 
   - [x] Data da Adesão
   - [x] Botões de Ação 
      - [ ] Link para página de GESTÃO do município
- [x] Paginação da Tabela
- [ ] Itens por página

**Comment by luizfpinheiro** [comment]
# Especificação

A visualização das informações em formato tabular permitirá aos gestores e cidadãos ter acesso facilitado as informações referentes a cada estado/município cadastrado no SNC.

## Interface
- Tabela
- Colunas da Tabela
   - Cidade/UF
   - Situação da Adesão
   - Data da Adesão
   - Botões de Ação
      - Link para a tela de detalhe do município
- Paginação da Tabela
- Itens por página

### Interface
A interface deve conter a [Barra Brasil](https://barra.brasil.gov.br), o cabeçalho do sistema, o componente de pesquisa e a tabela, todos encontram-se representados na identidade visual construída para o projeto e podem ser acessados neste [link](https://www.figma.com/file/R5Gcc6mWqpBkuXVuhoNzz0Dj/verSNC).

### Tabela
A tabela tem o objetivo de apresentar de maneira mais fácil as informações relacionadas aos municípios que aderiram ao SNC.

### Colunas
As colunas pertencentes à tabela são as seguintes: município/UF, situação da adesão, data da adesão, botões de ação.

### Paginação
Os itens devem ser apresentados em um total de 10 itens por página por padrão, havendo a possibilidade de serem exibidos em quantidade diferente através da escolha do número de itens por página.

### Itens por página
O usuário poderá definir a quantidade de itens a serem apresentados na tabela. (Exemplo: 5 , 10 ou 25 itens por página.)

**Comment by volthier** [comment]
Pendente em espera da refatoração da base de dados. [FIX]
