### ISSUE TITLE
Filtros avançados

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#85]
Eu como gestor do MinC quero poder combinar vários filtros dessa forma conseguirei encontrar os registros de forma simplificada.

Alguns filtros: região, situação adesão, ranges de data, componentes, ativo/inativo, etc

- [x]  Template da busca
- [x]  Busca inicial (Simples = Município e UF)
- [x]  Troca entre busca Simples e Avançada(Filtros)

Ps: Requisitado acréscimo ao filtro
- Situação de institucionalização/situação do plano de trabalho

**Comment by AnaOlivei** [comment]
Situação de implementação (situação do plano de trabalho)

**Comment by matheusbsilva** [comment]
Range de datas -> Buscar pelos municípios aderidos da data x a data y.

**Comment by matheusbsilva** [comment]
Range de dados resolvido em https://github.com/culturagovbr/sistema-nacional-cultura/pull/142/commits/d72a9b9e59efc8d3f8e691453c1b19078c38adbc

**Comment by volthier** [comment]
Situação de institucionalização (situação do plano de trabalho)

@AnaOlivei O Filtro recebeu um card para tratativa #157
