### ISSUE TITLE
Ordenar resultados 

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/sistema-nacional-cultura#86]
Eu como gestor do MinC quero ordenar de várias formas o resultado da pesquisa dessa forma a navegação pelos registros se torna mais simplificada

Alguns campos para ordenação: datas, região, UF, situação, etc

**Comment by matheusbsilva** [comment]
@luizfpinheiro qual a situação dessa Issue?

**Comment by luizfpinheiro** [comment]
@matheusbsilva É possível ordenar **alfabeticamente** pelo nome do Município e Situação da Adesão. Também é possível ordenar pela Data de Adesão.
