### ISSUE TITLE
Implementar o deploy facilitado em homologação

### ISSUE THREAD

**Issue by decko** [culturagovbr/sistema-nacional-cultura#91]
Eu, como Desenvolvedor UFABC, gostaria de publicar facilmente novas versões do SNC assim que o código for testado pelo bot de Integração.

**Critérios de Aceitação:**

- [x] Conseguir publicar manualmente com um comando
- [ ] Implementar o job no Jenkins para publicação automatizada

**Comment by matheusbsilva** [comment]
Atualmente os passos para publicação de software no ambiente de homologação são os seguintes:

1. Entrar no diretório da aplicação
```bash
cd /diretorio/raiz/do/projeto
```

2. Puxar o código atualizado da branch dev do GitHub(**problema com permissões**)
```bash
sudo git pull origin dev
```

3. Ativar o ambiente virtual:
```bash
source activate
```

4. Atualizar as dependências instaladas(**problema com permissões**)
```bash
sudo pip install -r requirements.txt
```

5. Fazer as migrações
```bash
python3 manage.py makemigrations
```

6. Rodar as migrações
```bash
python3 manage.py migrate
```

6. Coletar os arquivos estáticos(**problema com permissões**)
```bash
pyhton3 manage.py collectstatic --noinput
```

7. Reiniciar o servidor
```bash
sudo service httpd restart
```

**Problema com permissões**: Atualmente algumas pastas estão com permissões erradas impossibilitando a execução de alguns comandos.

**Comment by decko** [comment]
Não foi possível desenvolver o deploy como apenas um comando, apesar de termos simplificado o processo como um todo.

Dentre os avanços, apontamos:
* 12factors
* pipenv
* Sentry
* Jenkins

## 12factors
Com o django-environ, reduzimos o numero de arquivos de configuração e configuramos para q a aplicação se configure de acordo com o seu ambiente, seja desenvolvimento, homologação ou produção, de acordo com algumas variáveis de ambiente.

## pipenv
A partir de agora, o projeto utiliza pipenv, o novo gerenciador de ambientes/pacotes do Python. Com apenas um comando, ele instancia um novo virtualenv e instala os pacotes na versão especificada.
Tivemos que exportar como variável de ambiente um parâmetro do pipenv para q ele criasse o virtualenv dentro do próprio diretório da aplicação:
```bash
export PIPENV_VENV_IN_PROJECT=True
```
Assim, qualquer comando do pipenv faz referência ao virtualenv instanciado dentro do diretório da aplicação em ".venv".
Ainda, um dos pacotes utilizados tem origem direta no repositório git do mantenedor. Dessa forma, o pipenv instalada automaticamente o Django 2.0.1, q é a ultima versão. Devido a isso, é necessário forçar o downgrade do Django devido à algumas bibliotecas. Este é um ponto que deve ser tratado como débito técnico e ter prioridade elevada.

## Sentry
Com o Sentry, a aplicação passa a ter gestão de quaisquer exceções disparadas. Todos os membros do time possuem acesso, e novos membros podem pedir acesso diretamente ao Coordenador de Desenvolvimento do MinC.

## Jenkins
Criamos um Freestyle Project para executar o job de deploy para Homologação.
Basicamente com o seguinte script:
```bash
/usr/local/bin/pip3.4 install --user --upgrade pipenv
export PATH=$PATH:~/.local/bin
export PIPENV_VENV_IN_PROJECT=True
echo SECRET_KEY='SECRET_KEY_DO_PROJETO' > snc/.env
echo DEBUG=False >> snc/.env
echo DJANGO_EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend >> snc/.env
echo DATABASE_URL=CONFIG_DO_BANCO_DE_DADOS >> snc/.env
echo ALLOWED_HOSTS='HOSTS_DA_APLICAÇÃO'
echo RAVEN_DSN_URL=CONFIG_DO_ENDPOINT_SENTRY_DA_APP >> snc/.env
pipenv install
pipenv install django==1.8.18
pipenv run ./manage.py makemigrations
pipenv run ./manage.py migrate
pipenv run ./manage.py collectstatic --noinput
vim "+x" snc/wsgi.py
```

A ultima linha faz com q o arquivo wsgi.py seja alterado para que o servidor de aplicação reinicie automaticamente após o processo de deploy. A principio, o build do Jenkins precisa ser iniciado manualmente. Fica como débito técnico a implementação de um pipeline de deploy continuo.
