### ISSUE TITLE
Corrigir caminho raíz do projeto em settings.py e configurar raven pra rodar somente em produção

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/sistema-nacional-cultura#94]
A variável ROOT_DIR presente em settings.py não está referenciando o caminho correto para a raíz do projeto. 
A lib Raven deve ser usada somente em produção e atualmente está configurada para sempre ser usada.

**Comment by decko** [comment]
Raven foi configurada para Homologação e Produção, buscando as informações no caminho correto.
Os caminhos para MEDIA, STATIC e STATIC_ROOT foram ajustados obedecendo os novos parâmetros.
